.\" $Id: geese_pick.1,v 1.14 2010-09-14 21:37:36 grahn Exp $
.\" $Name:  $
.
.ss 12 0
.
.TH geese_pick 1 "SEP 2010" "Geese" "User Manuals"
.
.SH "NAME"
geese_pick \- pick coordinates from digital maps
.
.SH "SYNOPSIS"
.B geese_pick
.RB [ \-f
.IR mapping-file ]
.I map-file
.br
.B geese_pick
.B \-w
.I world-file
.I map-file
.br
.B geese_pick
.B --version
.br
.B geese_pick
.B --help
.
.SH "DESCRIPTION"
.B geese_pick
is a small interactive utility for picking coordinates from
digital maps, given
.IR map-file ,
the actual image file containing the map,
and georeferencing information.
.P
The georeferencing information can come either from the map's
.BR "world file" ,
or from
.I mapping-file
which carries similar information, but is specific for
.B geese
and describes how many images map onto the real world.
.
.SH "OPTIONS"
.IP \-f\ \fImapping-file
A mapping file (see below) describing a number of images and the
geographical areas they cover. If
.I map-file
isn't one of them, geese_pick searches for a world file
matching it instead.
.
.IP \-w\ \fIworld-file
Use the mapping provided by
.IR world-file .
.
.SH "USAGE"
.B geese_pick
relies on John Bradley's excellent
.BR xv (1)
image viewer,
and in particular its support for pointing at a pixel
and copying its coordinate (among other things) to the X clipboard.
This action is by default bound to the middle mouse button,
and works correctly even if
.BR xv 's
window has been resized or cropped.
.P
When this string is pasted into stdin, the pixel coordinate
is translated to the world coordinate system and printed
(several times, rounded in different ways
so you can pick the one you want).
The distance to the previously selected coordinate is also shown.
.P
.ft CW
.nf
one pixel is 5.0 m wide
the map covers 138.31 km²
1209,1118 =   4,  2,  4  #040204  (300  50   1 HSV)  [    0,    0]
1m: 6441591 1362845; 10m: 644159 136285; 100m: 64416 13628; 1km: 6442 1363
1192,1129 = 252,254,252  #fcfefc  (120   0  99 HSV)  [    0,    0]
1m: 6441536 1362760; 10m: 644154 136276; 100m: 64415 13628; 1km: 6442 1363
    101m from previous coordinate
.fi
.
.SH "MAPPING FILE FORMAT"
This file contains a series of entries describing different maps.
It is line-oriented, with entries separated by empty lines.
Lines starting with
.B #
are comment lines, and are ignored.
.P
An example entry:
.IP
.ft CW
.nf
luttra_n.png
b3f1b2e3fcafeb2c14f43d7261e0d62a
847 x 367
6450000 1368000 -> 183, 336
6451000 1370000 -> 775,  43
.fi
.P
The things needed to actually describe a map are:
.
.IP \- 2m
One or more file names, with the path stripped.
If a map is known under many names (perhaps there are color and grayscale,
PNG and JPEG versions) it is useful to list them all
(on separate lines).
.
.IP \-
Zero or more MD5 checksums, as generated by e.g.
.BR md5sum (1).
If a map entry has checksums, one of them must match the file provided to
.BR geese_pick .
The purpose of this is to minimize the risk of picking the wrong combination
of image and map entry (perhaps someone scaled or rotated the image file
since it was georeferenced), and getting insane coordinates as a result.
.
.IP \-
Image dimensions in pixels, on the form
.IB width \ x\  height\fR.
.
.IP \-
Two mappings from world to pixel coordinates, on the form
\fInorth east \fB\[->] \fIx\fB, \fIy\fR.
These are enough to describe the mapping
even if the image is rotated versus the coordinate system\(em\
as if we had taken a flat Earth, put it rather sloppily
in God's Great Xerox Machine, and pressed the button.
.
.SH "WORLD FILE FORMAT"
A world file is a (MS-DOS) text file with six numbers, one per line,
defining an
.I "affine transformation"
from pixel coordinates to map coordinates:
.IP
.ft CW
.nf
A  5.000000      coord = AB pixel + C
D  0                     DE         F
B  0
E  -5.000000
C  1356800.500000
F  6447181.500000
.fi
.P
World files are named by either appending a
.B w
to the map image's name, or appending it after removing the middle character
of the name's three-letter extension.
Typical names are
.B foo.jpgw
or
.B foo.jgw .
.P
Apart from those,
.B geese_pick
also searches for
.B foo.tfw
(in case the original map once was a TIFF file)
and it also searches for these names in subdirectories
(in case you store all your maps in a directory and all your world files
in a subdirectory).
.
.SH "NOTES"
Many things contribute to errors when using this approach to finding coordinates:
inaccurate maps, bad original mapping, rounding errors.
Unfortunately,
.B geese_pick
provides no means to estimate the size of the errors (1m? 10m? 100m?).
Use with care and good judgement.
.P
The world file format is more flexible than geese_pick, in that it can describe
e.g. shearing and different scalings on the x and y axis.
Such mappings are surely rare or nonexistant in practice, but if you stumble
across one, geese_pick will silently produce incorrect results.
.
.SH "AUTHOR"
J\(:orgen Grahn
.I \[fo]grahn+src@snipabacken.se\[fc]
.
.SH "SEE ALSO"
.BR xv (1),
.BR geese_plot (1),
.BR geese_world (1),
.BR md5sum (1).
Wikipedia:
.BR "World file" .
