.\" $Id: geese_world.1,v 1.2 2010-09-18 09:17:27 grahn Exp $
.\" $Name:  $
.
.
.ss 12 0
.
.
.TH geese_world 1 "SEP 2010" "Geese" "User Manuals"
.
.SH "NAME"
geese_world \- georeferencing digital maps
.
.SH "SYNOPSIS"
.B geese_world
.BI \-f\  mapping-file
.I map-file
.br
.B geese_pick
.B --version
.br
.B geese_pick
.B --help
.
.SH "DESCRIPTION"
.
.SH "OPTIONS"
.IP \-
.
.SH "USAGE"
.
.SH "AUTHOR"
J\(:orgen Grahn
.IR \[fo]grahn+src@snipabacken.se\[fc] .
License: GNU GPL.
.
.SH "SEE ALSO"
.BR xv (1),
.BR geese_pick (1),
.BR geese_plot (1).
