.\" $Id: geese_pick.1,v 1.4 2005-01-04 22:48:51 grahn Exp $
.\" $Name:  $
.\" 
.\"
.TH geese_pick 1 "SEP 2004" "Geese" "User Manuals"
.SH "NAME"
geese_pick \- pick coordinates from digital maps
.SH "SYNOPSIS"
.B geese_pick
.RI [ \-V ]
.BI \-f\  mapping-file
.I map-file
.
.SH "DESCRIPTION"
.B geese_pick
is a small interactive utility for picking coordinates from
digital maps, given
.IR map-file ,
the actual image file containing the map,
and
.IR mapping-file ,
which describes how one or more images map onto the real world.
.P
Doing this with a real paper map is difficult, boring and
error-prone, even if it has a superimposed grid.
On the other hand, it is relatively simple and safe to
scan, borrow or buy maps and finding their coordinate systems.
.
.SH "OPTIONS"
.IP \-f\ \fImapping-file
The mapping file, describing a number of images and the
geographical areas they cover.
See below for details.
.
.IP \-V
Print version information and exit.
.
.SH "USAGE"
.B geese_pick
relies on John Bradley's excellent
.BR xv (1)
image viewer,
and in particular its support for pointing at a pixel
and copying its coordinate (among other things) to the X clipboard.
This action is by default bound to the middle mouse button,
and works correctly even if
.BR xv 's
window has been resized or cropped.
.P
When this string is pasted into stdin, the pixel coordinate
is translated to the world coordinate system and printed
(several times, rounded in different ways
so you can pick the one you want).
.
.SH "MAPPING FILE FORMAT"
This file contains a series of entries describing different maps.
It is line-oriented, with entries separated by empty lines.
Lines starting with
.B #
are comment lines, and are ignored.
.P
An example entry:
.IP
.ft CW
.nf
luttra_n.png
b3f1b2e3fcafeb2c14f43d7261e0d62a
847 x 367
6450000 1368000 -> 183, 336
6451000 1370000 -> 775,  43
.fi
.P
The things needed to actually describe a map are:
.
.IP \- 2m
One or more file names, with the path stripped.
If a map is known under many names (perhaps there are color and grayscale,
PNG and JPEG versions) it is useful to list them all
(on separate lines).
.
.IP \-
Zero or more MD5 checksums, as generated by e.g.
.BR md5sum (1).
If a map entry has checksums, one of them must match the file provided to
.BR geese_pick .
The purpose of this is to minimize the risk of picking the wrong combination
of image and map entry (perhaps someone scaled or rotated the image file
since it was coordinated), and getting insane coordinates as a result.
.
.IP \-
Image dimensions in pixels, on the form
.IB width \ x\  height\fR.
.
.IP \-
Two mappings from world to pixel coordinates, on the form
\fInorth east \fB-> \fIx\fB, \fIy\fR.
These are enough to describe the mapping
even if the image is rotated versus the coordinate system\(em\
as if we had taken a flat Earth, put it rather sloppily
in God's Great Xerox Machine, and pressed the button.
.
.SH "NOTES"
Many things contribute to errors when using this approach to finding coordinates:
inaccurate maps, bad original mapping, rounding errors.
Unfortunately,
.B geese_pick
provides no means to estimate the size of the errors (1m? 10m? 100m?).
Use with care and good judgement.
.
.SH "AUTHOR"
J\(:orgen Grahn
.I <jgrahn@algonet.se>
.
.SH "SEE ALSO"
.BR xv (1),
.BR geese_plot (1),
.BR md5sum (1).
