.\" $Id: geese_plot.1,v 1.8 2009-09-16 18:49:20 grahn Exp $
.\" $Name:  $
.\" 
.\"
.TH geese_plot 1 "AUG 2007" "Geese" "User Manuals"
.SH "NAME"
geese_plot \- plot coordinates on maps
.SH "SYNOPSIS"
.B geese_plot
.RI [ \-V ]
.RB [ \-t
.IR format ]
.BI \-f\  mapping-file
.I map-file
.
.SH "DESCRIPTION"
.B geese_plot
is a small interactive utility for plotting coordinates onto
digital maps, given
.IR map-file ,
the actual image file containing the map,
and
.IR mapping-file ,
which describes how one or more images map onto the real world.
.
.SH "OPTIONS"
.IP \-f\ \fImapping-file
The mapping file (see
.BR geese_pick (1)
for details).
.
.IP \-t\ \fIformat
Render the plotted map in graphics format
.IR format ,
which can be either
.I jpeg
or
.IR png .
Default is
.IR jpeg ,
which generates much faster, but loses some detail.
.IP
Other formats such as
.IR gif ,
.I ppm
and
.I tiff
are also likely to be supported; the name is simply passed through to the
.SM PIL
library which encodes the image.
.
.IP \-V
Print version information and exit.
.
.SH "USAGE"
.B geese_plot
features a really simple command-line interface.
Input is in the form
.IP
.I coordinate
.br
.B show
.br
.B bullseye
.BR white | black
.I width
.br
.B help
.br
.B exit
.P
The
.B show
command displays the map with the coordinates plotted
as small circles,
using John Bradley's excellent
.BR xv (1)
image viewer.
.P
The
.B bullseye
command controls the color and size of the circles.
You might need to use this for readability,
depending on the size and coloring scheme
of the map, and the number of points to plot.
.P
Coordinates are on the form
.IP
.I
north\ east
.P
and may have meter-resolution or less:
.IP
.nf
.I 6448158\ 1370286
.I 64481\ 13702
.fi
.P
Naturally, EOF (Control-D) or
.B exit
exits
.BR geese_plot .
.
.SH "AUTHOR"
J\(:orgen Grahn
.I <grahn+src@snipabacken.se>
.
.SH "SEE ALSO"
.BR geese_pick (1),
.BR xv (1).
