.\" $Id: geese_world.1,v 1.7 2010-09-23 18:28:46 grahn Exp $
.\" $Name:  $
.
.
.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.
.TH geese_world 1 "SEP 2010" "Geese" "User Manuals"
.
.SH "NAME"
geese_world \- show georeferencing map information
.
.SH "SYNOPSIS"
.B geese_world
.RB [ \-f
.IR mapping-file ]
.I map-file
\&...
.br
.B geese_world
.RB [ \-f
.IR mapping-file ]
.B \-d
.I destination-map
.I source-map
\&...
.br
.B geese_world
.B --version
.br
.B geese_world
.B --help
.
.SH "DESCRIPTION"
In the first form,
.B geese_world
lists the georeferencing information for one or more
.IR map-file s,
in the same two formats as
.BR geese_ref (1).
This can be used to create world files or mapping file entries
(whichever doesn't exist) for the images.
.IP
.ft CR
.nf
luttra_n.png
b3f1b2e3fcafeb2c14f43d7261e0d62a
6451134.9 1367375.9 -> 0.0 0.0
6451148.7 1370761.1 -> 1000.0 0.0

3.3852
0.0138
0.0138
-3.3852
1367375.9
6451134.9
.fi
.PP
(The image width x height are unfortunately missing in the output
above; geese_world knows nothing about image file formats so it
cannot retrieve that information.)
.IP
.ft CR
.nf
luttra_n.png: scale by 0.999502 (99.95 %); rotate 0.11°
.fi
.PP
The second form describes which scaling and rotation you have to
apply to each
.I source-map
to be able to overlay it on
.I destination-map.
This can be used to create layered maps in drawing tools like
.IR "the GIMP" .
.
.SH "OPTIONS"
.BP \-f
A
.I mapping-file
describing the coordinate systems of the maps involved.
If omitted, the information must exist in world files instead, found according
to the same rules as
.BR geese_pick (1)
uses.
.BP \-d
The
.I destination-map
in the second form.
.
.SH "BUGS"
The mapping file output is based on the two fixed pixels
(0,\~0) and (1000,\~0) \- not on whatever is in the actual mapping file,
if one is the source of the information.
.
.SH "AUTHOR"
J\(:orgen Grahn
.IR \[fo]grahn+src@snipabacken.se\[fc] .
Licensed under the GNU General Public License.
.
.SH "SEE ALSO"
.BR geese_pick (1),
.BR geese_ref (1),
.BR geese_plot (1).
