.\" $Id: geese_ref.1,v 1.6 2011-02-06 15:05:54 grahn Exp $
.\" $Name:  $
.
.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.
.TH geese_ref 1 "FEB 2011" "Geese" "User Manuals"
.
.SH "NAME"
geese_ref \- georeference digital maps
.
.SH "SYNOPSIS"
.B geese_ref
.RB [ \-f
.IR mapping-file ]
.I reference-map
.I map
.br
.B geese_ref
.B --version
.br
.B geese_ref
.B --help
.
.SH "DESCRIPTION"
.B geese_ref
lets you
.I georeference
a digital map, i.e. specify how the image is scaled, rotated etc compared to
some coordinate system like RT90.
You do it by specifying two points on
.I reference-map
(which has already been georeferenced)
and the same two point on
.I map
(the one you want to georeference).
.PP
The result is printed on standard output in two forms:
information which can form an entry in a mapping file,
and six numbers which form a world file.
.IP
.ft CW
.nf
luttra_n.png
b3f1b2e3fcafeb2c14f43d7261e0d62a
847 x 367
6450000 1368000 -> 183 336
6451000 1370000 -> 775  43

5.000000
0
0
-5.000000
1356800.500000
6447181.500000
.fi
.PP
Since you only give two points, the transformation must be a simple
scaling and rotation. And you better be careful with the positioning,
choose points far apart, and have a good reference.
.PP
The
.I reference-map
must have the same kind of georeferencing information that
.BR geese_pick (1)
needs; either an entry in
.IR mapping-file ,
or a valid world file.
.
.SH "OPTIONS"
.BP \-f
A
.I mapping-file
describing the coordinate system of the reference map
(and possibly other maps).
If omitted, there must be a world file for the map, found according
to the same rules as
.BR geese_pick (1)
uses.
.
.SH "AUTHOR"
J\(:orgen Grahn
.IR \[fo]grahn+src@snipabacken.se\[fc] .
.
.SH "LICENSE"
The GNU General Public License (GPL) version 2 or (at your option) version 3.
.
.SH "SEE ALSO"
.BR xv (1),
.BR geese_pick (1).
